// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:59f0ddd8a626838e49a14c5d14146f40b006ba07ac6a0a2241238b76d9056276

export type Input = {
  /** Repo-relative directory of the ui lib that gets the directive (e.g. libs/web/catalog/ui) */
  lib: string;
  /** Directive name, dash-case (e.g. highlight); the selector is [<prefix>Highlight] and the class <Prefix>Highlight */
  name: string;
  /** Folder under src/lib that holds the files, dash-case. Omit to use the name; set it to group related artifacts (e.g. experiments for a service and its directive) */
  folder?: string;
};
