// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:4933cb5c958a68d732c3c5d20569b95d1471f945c7aff3a113aa363cc9bffa06

export type Input = {
  /** Repo-relative directory of the ui lib that gets the directive (e.g. libs/web/catalog/ui) */
  lib: string;
  /** Directive name, dash-case (e.g. highlight); the selector is [<prefix>Highlight] and the class <Prefix>Highlight */
  name: string;
};
