// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:b8a09e338a71311831a7ac5ab1a45ffa5310934aec898685bcb6684387175cf8

export type Input = {
  /** Bounded context, dash-case (e.g. ordering) */
  context: string;
};
