// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:03e05d2eb5d2abd164d2801d4e0b055fa27d2d02cc9c7d405e44e7e22cccaca6

export type Input = {
  /** Repo-relative directory of the Angular lib that gets the service (e.g. libs/web/catalog/data-access) */
  lib: string;
  /** Service name, dash-case (e.g. order-store); the class is OrderStore */
  name: string;
  /** Comma-separated state fields as name:type, type string, number, boolean or one of them followed by [] (e.g. count:number,ids:string[]). Each becomes a private writable signal exposed as a readonly signal */
  fields?: string;
  /** Folder under src/lib that holds the files, dash-case. Omit to use the name; set it to group related artifacts (e.g. experiments for a service and its directive) */
  folder?: string;
};
