// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:42baee8c8644c0957747ffc4b8928320f73aac9e4e737f33cfe9c9abb1b1d7f1

export type Input = {
  /** Repo-relative directory of the Angular lib that gets the service (e.g. libs/web/catalog/data-access) */
  lib: string;
  /** Service name, dash-case (e.g. order-store); the class is OrderStore */
  name: string;
  /** Comma-separated state fields as name:type, type string, number, boolean or one of them followed by [] (e.g. count:number,ids:string[]). Each becomes a private writable signal exposed as a readonly signal */
  fields?: string;
  /** Folder under src/lib that holds the files, dash-case. Omit to use the name; set it to group related artifacts (e.g. experiments for a service and its directive) */
  folder?: string;
};
