// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:88bbba03cf1944ba59fce41c96d0627db08511324e8ecfc19c9ac3e364d95dbb

export type Input = {
  /** Repo-relative directory of the Angular lib that gets the service (e.g. libs/web/catalog/data-access) */
  lib: string;
  /** Service name, dash-case (e.g. order-store); the class is OrderStore */
  name: string;
  /** Comma-separated state fields as name:type, type string, number, boolean or one of them followed by [] (e.g. count:number,ids:string[]). Each becomes a private writable signal exposed as a readonly signal */
  fields?: string;
};
