// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:bbab2e21621c33cd95571546029073a380a884cdfb02170ee74131182c1d4934

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
};
