// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:925e76562b3de8c3cc6e78012aa7b98cfaf98529a7beb4658097d78beaae1972

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** Use case in PascalCase, a business action from the context's glossary (e.g. IssueInvoice) */
  name: string;
  /** Comma-separated driven ports the use case needs, PascalCase. Omit to read them from the use case's row in domain-model.md; a flag may only agree with the doc. Each port must already exist (hex-driven-port). */
  driven_ports?: string;
};
