// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:a38c4efeef6e052db3a495a8efa147f978738025c5db0dd1a84a25caa9d984cc

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** Use case in PascalCase, a business action from the context's glossary (e.g. IssueInvoice) */
  name: string;
};
