// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:a0652e33bdfb6a8fa51b0d000cdeff1a8649fcb43d9cf4721dcbe27606f30169

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** One sentence: what this context is responsible for, in business words */
  purpose: string;
  /** Subdomain class, decides design investment. core: differentiates the product; supporting: needed, not differentiating, cannot be bought; generic: a vendor could provide it */
  subdomain_class: "core" | "supporting" | "generic";
  /** Criticality, decides verification rigor. high: a bug is a financial error, a confidentiality breach or data loss */
  criticality: "low" | "medium" | "high";
  /** Volatility, how often the rules change; decides how much cleanup is worth */
  volatility: "low" | "medium" | "high";
  /** Whether the person confirmed the classification. Omitted means confirmed. assumed: the values are annotated as assumptions and the strict level applies until they confirm it */
  classification_status?: "confirmed" | "assumed";
  /** Contexts this one depends on, comma-separated <context>:<relationship> with relationship customer-supplier, conformist or acl (e.g. billing:conformist,shipping:acl). Each context must already exist. Written to the docs Context map and declared in the lint boundaries */
  context_map?: string;
  /** Comma-separated subdomains, dash-case (e.g. invoicing,payouts). Empty: the context is its single subdomain and its docs and code stay inline; several: one docs folder and one code folder per subdomain. */
  subdomains?: string;
};
