// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:9140a0075b65d7916c6558ecd5f8a3b286284c53c903b981d3cb8e8bc6312481

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** One sentence: what this context is responsible for, in business words */
  purpose: string;
  /** Subdomain class, decides design investment. core: differentiates the product; supporting: needed, not differentiating, cannot be bought; generic: a vendor could provide it */
  subdomain_class: "core" | "supporting" | "generic";
  /** Criticality, decides verification rigor. high: a bug is a financial error, a confidentiality breach or data loss */
  criticality: "low" | "medium" | "high";
  /** Volatility, how often the rules change; decides how much cleanup is worth */
  volatility: "low" | "medium" | "high";
  /** Whether the person confirmed the classification. Omitted means confirmed. assumed: the values are annotated as assumptions and the strict level applies until they confirm it */
  classification_status?: "confirmed" | "assumed";
  /** Tactical model. Omitted means full. deferred: Aggregates carries a Not applicable paragraph (Transaction Script) instead of a model, with a follow-up to name its trigger */
  tactical?: "full" | "deferred";
  /** Relations to other contexts, free text (e.g. downstream of billing (conformist); upstream of shipping) */
  context_map?: string;
  /** Comma-separated subdomains, dash-case (e.g. invoicing,payouts). Empty: the context is its single subdomain and its docs and code stay inline; several: one docs folder and one code folder per subdomain. */
  subdomains?: string;
};
