// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:74d71d2022f32c81a5c1e58f02ed1d01e4a91f91ea7067d62aaf9921d36d6869

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** Port name in PascalCase, in the slice's own language (e.g. InvoiceRepository, Clock) */
  name: string;
};
