// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:f75f530c753231bc98c21154f429b526b9d8846f67cc3f379009dbbf281f5c75

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** Port name in PascalCase, in the slice's own language (e.g. InvoiceRepository, Clock) */
  name: string;
  /** What answers the port: memory (an in-memory adapter for now) or context (another bounded context's barrel). Omit to read it from the port's Adapter today cell in domain-model.md, which starts with Memory or @<context> */
  kind?: "memory" | "context";
  /** For kind=context: the bounded context whose barrel the adapter calls, dash-case (e.g. ledger) */
  provider?: string;
};
