// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:d39571cee700460c9963fd2de2337ea0c2db6ed9149a96fab7a37f92611c2b22

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** Port name in PascalCase, in the slice's own language (e.g. InvoiceRepository, Clock) */
  name: string;
  /** What answers the port: memory (an in-memory adapter for now) or context (another bounded context's barrel). Omit to read it from the port's Adapter today cell in domain-model.md, which starts with Memory or @<context> */
  kind?: "memory" | "context";
  /** For kind=context: the bounded context whose barrel the adapter calls, dash-case (e.g. ledger) */
  provider?: string;
};
