// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:f7ea0b47d8ae8bc997c9394138fef8965e76c3a3db104055a5d46c936ef738c0

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
};
