// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:35320bc719cfd6f4ee9732a0c86c872f85c5ae32b071073a0d37676b50581b42

export type Input = {
  /** Lib name, dash-case (e.g. design-system); the lib is libs/web/shared/<name> */
  name: string;
  /** Angular selector prefix, lowercase letters (e.g. ds): components are <prefix>-name, directives [prefixName] */
  prefix: string;
  /** DDD layer of the lib, becomes its type: tag. Omitted means ui */
  layer?: "ui" | "data-access" | "domain";
};
