// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:1826441ae9ee261acf4cd009c0efd69e671421561255a704d389d30de6f29857

export type Input = {
  /** Lib name, dash-case (e.g. design-system); the lib is libs/web/shared/<name> */
  name: string;
  /** Angular selector prefix, lowercase letters (e.g. ds): components are <prefix>-name, directives [prefixName] */
  prefix: string;
};
