// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:f803807bad381341884eef68e1026c4ce631cb674fb61234a6f121ad51917991

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** REST resource the route hangs from, dash-case; becomes the controller path and file base (e.g. invoices gives invoices.controller.ts under /api/invoices) */
  resource: string;
  /** HTTP method */
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  /** Use case the route drives, PascalCase; must already be exported by the context barrel (hex-use-case). Omit to read it from the route's Driving adapters row */
  use_case?: string;
  /** Path under the resource (default: /); needed only when the resource has several rows for the method */
  path?: string;
  /** Success status the handler answers. Omit to read the first 2xx of the row's Answers cell; Nest's default (201 for POST, 200 otherwise) needs no decorator */
  status?: "200" | "201" | "202" | "204";
};
