// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:1189d11ec65493a8923fa4b7a35850f86b53ede568cfbf549b818413811f97d1

export type Input = {
  /** Bounded context, dash-case (e.g. billing) */
  context: string;
  /** Subdomain slice inside the context, dash-case (e.g. invoicing) */
  slice: string;
  /** REST resource the route hangs from, dash-case; becomes the controller path and file base (e.g. invoices gives invoices.controller.ts under /api/invoices) */
  resource: string;
  /** HTTP method */
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE";
  /** Path under the resource (default: /); needed only when the resource has several rows for the method */
  path?: string;
};
