// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:5b4a3e6103326cdae7d516bea3f7f74d6232765061e3a6fe7dd687d7563207a9

export type Input = {
  /** Repo-relative directory of the Angular lib that gets the component (e.g. libs/web/catalog/ui) */
  lib: string;
  /** Component name, dash-case (e.g. order-card); the class is OrderCard and the selector <prefix>-order-card */
  name: string;
  /** Presentational only. Comma-separated required signal inputs as name:type, type string, number, boolean, a PascalCase type or any of them followed by [] (e.g. label:string,lines:OrderLine[]). A PascalCase type needs type_import */
  inputs?: string;
  /** Presentational only. Comma-separated signal outputs, camelCase, optionally name:type with the same types as inputs (e.g. dismissed,added:AddLine). Without a type the output has no payload */
  outputs?: string;
  /** Module the PascalCase input and output types are imported from with `import type` (e.g. @demo/web-ordering-domain). Required when any input or output uses one */
  type_import?: string;
  /** Folder under src/lib that holds the files, dash-case. Omit to use the name; set it to group related artifacts (e.g. experiments for a service and its directive) */
  folder?: string;
};
