// AUTO-GENERATED by pbuilder-codegen — do not edit. Regenerate: pbuilder-codegen <package-dir>
// @schema-digest sha256:73fc929f2471682860dfbf42525aeb89328be437058557f3408fc939ea421d7c

export type Input = {
  /** Repo-relative directory of the Angular lib that gets the component (e.g. libs/web/catalog/ui) */
  lib: string;
  /** Component name, dash-case (e.g. order-card); the class is OrderCard and the selector <prefix>-order-card */
  name: string;
  /** container (owns data access, lives in a feature lib) or presentational (inputs and outputs only, lives in a ui lib). Omit to read it from the lib's type tag; a flag may only agree with it */
  kind?: "container" | "presentational";
  /** Presentational only. Comma-separated required signal inputs as name:type, type string, number or boolean (e.g. label:string,count:number) */
  inputs?: string;
  /** Presentational only. Comma-separated signal outputs without payload, camelCase (e.g. selected,dismissed) */
  outputs?: string;
  /** Folder under src/lib that holds the files, dash-case. Omit to use the name; set it to group related artifacts (e.g. experiments for a service and its directive) */
  folder?: string;
};
